version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_SOCKET_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend